# Generated by Django 4.1.3 on 2022-11-18 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0015_auto_20200516_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 11, 18, 11, 53, 32, 324129, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
