# Generated by Django 4.1.3 on 2022-11-18 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0016_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 11, 18, 12, 4, 38, 686799, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
