# Generated by Django 4.1 on 2022-11-11 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travello", "0018_alter_transactions_date_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("wallet_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(default="0", max_length=20)),
                ("balance", models.CharField(default="0", max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="transactions",
            name="Date_Time",
            field=models.CharField(
                default=datetime.datetime(
                    2022, 11, 11, 5, 44, 51, 454923, tzinfo=datetime.timezone.utc
                ),
                max_length=19,
            ),
        ),
    ]
