# Generated by Django 4.1 on 2022-11-20 11:20

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("travello", "0025_alter_transactions_date_time_user"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="User2",),
        migrations.AlterField(
            model_name="transactions",
            name="Date_Time",
            field=models.CharField(
                default=datetime.datetime(
                    2022, 11, 20, 11, 20, 49, 226670, tzinfo=datetime.timezone.utc
                ),
                max_length=19,
            ),
        ),
    ]
