# Generated by Django 4.1 on 2022-11-20 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travello", "0026_rename_user_user2_alter_transactions_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="Date_Time",
            field=models.CharField(
                default=datetime.datetime(
                    2022, 11, 20, 11, 45, 51, 295316, tzinfo=datetime.timezone.utc
                ),
                max_length=19,
            ),
        ),
    ]
