# Generated by Django 4.1.3 on 2022-11-20 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0029_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 11, 20, 13, 33, 43, 945265, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
