# Generated by Django 4.1.3 on 2022-11-20 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0032_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed_desc',
            name='lat',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='detailed_desc',
            name='long',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 11, 20, 14, 28, 58, 675575, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
