# Generated by Django 4.1.3 on 2022-11-20 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0033_detailed_desc_lat_detailed_desc_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed_desc',
            name='lat',
            field=models.IntegerField(default=31.0546441),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='long',
            field=models.IntegerField(default=-17.7823932),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 11, 20, 14, 29, 7, 99033, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
