# Generated by Django 4.1.3 on 2022-11-20 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0039_alter_transactions_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailed_desc',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='detailed_desc',
            name='long',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 11, 20, 14, 38, 25, 562004, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
