# Generated by Django 4.1.3 on 2022-11-20 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0042_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed_desc',
            name='lat',
            field=models.IntegerField(default=31.0546441),
        ),
        migrations.AddField(
            model_name='detailed_desc',
            name='long',
            field=models.IntegerField(default=-17.7823932),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 11, 20, 14, 41, 30, 857090, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
