# Generated by Django 4.1.3 on 2022-11-20 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0043_detailed_desc_lat_detailed_desc_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 11, 20, 14, 42, 12, 264350, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
