# Generated by Django 4.1.3 on 2022-11-20 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0047_remove_detailed_desc_lat_remove_detailed_desc_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed_desc',
            name='lat',
            field=models.CharField(default=31.0546441, max_length=200),
        ),
        migrations.AddField(
            model_name='detailed_desc',
            name='long',
            field=models.CharField(default=-17.7823932, max_length=200),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 11, 20, 14, 46, 15, 151687, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
