# Generated by Django 4.1 on 2022-11-20 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travello", "0048_detailed_desc_lat_detailed_desc_long_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="Date_Time",
            field=models.CharField(
                default=datetime.datetime(
                    2022, 11, 20, 15, 54, 2, 952523, tzinfo=datetime.timezone.utc
                ),
                max_length=150,
            ),
        ),
    ]
