# Generated by Django 4.1.3 on 2022-11-27 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0049_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 11, 27, 9, 25, 32, 766354, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
